apiVersion: v1
kind: Pod
metadata:
  labels:
    run: django
    creation_method: manual
    env: dev
  name: django
spec:
  containers:
  - env:
    - name: DATABASE_URL
      value: postgres://<DB-USER>:<DB-PASSWORD>@<YOUR-HOST-IP>:<DB-PORT>/<DB-NAME>
    image: django_app:latest
    imagePullPolicy: IfNotPresent
    name: django
    ports:
    - containerPort: 80
      protocol: TCP